### ISSUE TITLE
`check_always()` documentation doesn't return expected outputs

### ISSUE THREAD

**Issue by Paulj1989** [Paulj1989/nice#8]
The `check_always()` function (recently developed by @rossellhayes) should return a "Nice!" whenever anything nice is output, and appears to be working as expected, however, the documentation doesn't show the nice outputs.

The example code isn't run in the documentation, so that's not really an issue, but it is a problem when you look at the [nice pkgdown site](https://paulj1989.github.io/nice/reference/check_always.html), which runs the example code and returns a 69, but without a "Nice!".

**Comment by rossellhayes** [comment]
This is a really tricky issue. Basically, task callbacks are only evaluated after a top-level function call, meaning they'll show up after you execute code in the console, but won't show up when code is evaluated in any internal process (e.g. rendering documentation, building a pkgdown site, knitting an Rmarkdown document, running tests). Normally, that behavior is desirable, since it ensures that `check_always()` will only affect your interactive experience and can't mess up anything you produce. But in this specific case, it's a problem.

The best solution I can think of is to essentially fake the examples section. Rather than using examples that are dynamically run by `pkgdown`, we can hardcode the output with comments. I've created a PR to do this (#9) if you're okay with that solution.

**Comment by rossellhayes** [comment]
This is also why the tests for `check_always()` are indirect. To properly test them from start-to-finish, we would need to do something like add a dependency on `callr` and evaluate the test code in a separate R process. I can throw together a PR that implements that as well if you're interested

**Comment by Paulj1989** [comment]
> This is a really tricky issue. Basically, task callbacks are only evaluated after a top-level function call, meaning they'll show up after you execute code in the console, but won't show up when code is evaluated in any internal process (e.g. rendering documentation, building a pkgdown site, knitting an Rmarkdown document, running tests).

Yeah I suspected the problem was something along these lines, but my interaction with task callbacks was limited so wasn't certain, and was also unsure if there was any solutions.

> The best solution I can think of is to essentially fake the examples section. Rather than using examples that are dynamically run by `pkgdown`, we can hardcode the output with comments. I've created a PR to do this (#9) if you're okay with that solution.

That makes sense. Don't think it's worth overthinking things given that the function works as expected and the error is really just a mismatch between the function and pkgdown.

> This is also why the tests for check_always() are indirect. To properly test them from start-to-finish, we would need to do something like add a dependency on callr and evaluate the test code in a separate R process. I can throw together a PR that implements that as well if you're interested

If you've got the time to put something together for this then sure! Don't feel any pressure to do so, given it's a very silly package, but any contributions definitely welcome.
